parameters:
  linestorm.blog.module.post.class:             LineStorm\BlogPostBundle\Module\PostModule
  linestorm.blog.module.post.article.class:     LineStorm\BlogPostBundle\Module\Component\ArticleComponent
  linestorm.blog.module.post.gallery.class:     LineStorm\BlogPostBundle\Module\Component\GalleryComponent
  linestorm.blog.module.post.tag.class:         LineStorm\BlogPostBundle\Module\Component\TagComponent

services:
  linestorm.blog.module.post:
    class: %linestorm.blog.module.post.class%
    tags:
      - { name: linestorm.blog.module }

  linestorm.blog.module.post.component.article:
    class: %linestorm.blog.module.post.article.class%
    tags:
      - { name: linestorm.blog.module.post.component }

  linestorm.blog.module.post.component.gallery:
    class: %linestorm.blog.module.post.gallery.class%
    tags:
      - { name: linestorm.blog.module.post.component }

  linestorm.blog.module.post.component.tag:
    class: %linestorm.blog.module.post.tag.class%
    tags:
      - { name: linestorm.blog.module.post.component }


  #
  # TWIG POST MODULE
  linestorm.blog.twig.module_post_extension:
    class: LineStorm\BlogPostBundle\Twig\PostExtension
    arguments: [ @linestorm.blog.module_manager, @service_container ]
    tags:
      - { name: twig.extension }
