#
# DEFAULT FORM TYPES
#
parameters: ~

services:

  #
  # Form Types
  #
  linestorm.cms.module.post.form.post:
        class: LineStorm\PostBundle\Form\PostFormType
        arguments: [@linestorm.cms.model_manager, @linestorm.cms.module_manager]
        tags:
            - { name: form.type, alias: linestorm_cms_form_post }

  linestorm.cms.module.post.form.category:
        class: LineStorm\PostBundle\Form\CategoryFormType
        arguments: [@linestorm.cms.model_manager]
        tags:
            - { name: form.type, alias: linestorm_cms_form_post_category }
