linestorm_blog_post_module_admin_list:
    pattern:  /
    defaults: { _controller: LineStormBlogPostBundle:Admin:list }

linestorm_blog_post_module_admin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: LineStormBlogPostBundle:Admin:edit }
    requirements:
       id: \d+

linestorm_blog_post_module_admin_view:
    pattern:  /{id}
    defaults: { _controller: LineStormBlogPostBundle:Admin:view }
    requirements:
       id: \d+

linestorm_blog_post_module_admin_create:
    pattern:  /new
    defaults: { _controller: LineStormBlogPostBundle:Admin:new }
