linestorm_blog_post_module_api_controller:
    type:     rest
    resource: LineStorm\BlogPostBundle\Controller\Api\PostController
    name_prefix:  linestorm_blog_post_module_api_

linestorm_blog_api_tag:
    type:     rest
    resource: LineStorm\BlogPostBundle\Controller\Api\TagController
    name_prefix:  linestorm_blog_post_module_api_

linestorm_blog_api_category:
    type:     rest
    resource: LineStorm\BlogPostBundle\Controller\Api\CategoryController
    name_prefix:  linestorm_blog_post_module_api_
